{% set version = "0.1.2" %}

package:
  name: "pyforest"
  version: "{{ version }}"

source:
  git_url: https://github.com/8080labs/pyforest.git
  git_rev: "{{ version }}"
  #path: ./

# build:
#   number: 0
#   script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - setuptools
    - pytest
    - pytest-cov
    - pytest-runner
  host:
    - pip
    - python
  run:
    - python

test:
  requires:
    - pytest
    - pytest-cov
    - pytest-runner
  imports:
    - pytest
    - pytest_cov

about:
  home: https://github.com/8080labs/pyforest
  license: MIT
  summary: Lazy-import of all popular Python Data Science libraries. Stop writing the same imports over and over again.
